### ISSUE TITLE
Exception while crawling

### ISSUE THREAD

**Issue by tatey** [tatey/translink#4]
Translink sometimes returns a page other than the one we're expecting. Thinking of wrapping this in an rescue and retrying the page again.

``` ruby
/Users/Tate/Code/Remote/translink/lib/translink/page/trip.rb:106:in `stop_times': undefined method `search' for #<Mechanize::File:0x007fb38b2eb008> (NoMethodError)
  from /Users/Tate/Code/Remote/translink/lib/translink/crawler.rb:15:in `block (2 levels) in crawl'
  from /Users/Tate/Code/Remote/translink/lib/translink/crawler.rb:13:in `each'
  from /Users/Tate/Code/Remote/translink/lib/translink/crawler.rb:13:in `block in crawl'
  from /Users/Tate/Code/Remote/translink/lib/translink/crawler.rb:11:in `each'
  from /Users/Tate/Code/Remote/translink/lib/translink/crawler.rb:11:in `crawl'
  from /Users/Tate/Code/Remote/translink/lib/translink/cli.rb:40:in `block in scrape'
  from /Users/Tate/Code/Remote/translink/lib/translink/db.rb:8:in `block in context'
  from /Users/Tate/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/dm-core-1.2.0/lib/dm-core.rb:263:in `block in repository'
  from /Users/Tate/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/dm-core-1.2.0/lib/dm-core/repository.rb:114:in `scope'
  from /Users/Tate/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/dm-core-1.2.0/lib/dm-core.rb:263:in `repository'
  from /Users/Tate/Code/Remote/translink/lib/translink/db.rb:5:in `context'
  from /Users/Tate/Code/Remote/translink/lib/translink/cli.rb:38:in `scrape'
  from /Users/Tate/Code/Remote/translink/lib/translink/cli.rb:16:in `run'
  from ./bin/translink:7:in `<main>'
```

**Comment by tatey** [comment]
This has been fixed. We now retry if we encounter an exception.
